### ISSUE TITLE
Can't import data when client runs on different host and server if it's bound to 0.0.0.0

### ISSUE THREAD

**Issue by WaaX** [pilosa/python-pilosa#131]
I'm using the latest python-pilosa version from github (fa8d70319a9b0008e20261f0bbc38dfaddd1affd) and the lastest pilosa server (506e9a2db7537fe784391a41603878247602830b).

My single node server is configured to bind http://0.0.0.0:10101. 
My python client is running on a different host.

When calling import_field, _import_data is called and fetches the list of nodes from the server. The server returns "0.0.0.0:10101" which the client attempt to connect and fails because from the client's side, 0.0.0.0 is not accessible (pilosa.exceptions.PilosaError: There are no available hosts).

I'm not sure what's the best approach to this situation:
- Update the python-pilosa documentation to mention to make sure the server is bound to a specific address and not 0.0.0.0
- Add a special case in _fetch_coordinator_node to use the client's current host if the list of nodes contains 1 entry and the host is different from the one used by the client
- Raise the exception with a help message (raise PilosaError("There are no available hosts, make sure the server bound address is accessible by the client))

**Comment by jaffee** [comment]
This is mainly a Pilosa issue which is slated for work in the current sprint: https://github.com/pilosa/pilosa/issues/1759

One of the proposed changes is that if Pilosa is configured to bind to 0.0.0.0, it will look at the actual addresses that it binds to and report one of those when asked for its status.

**Comment by travisturner** [comment]
@WaaX The work in #1832 on the server side improves the way pilosa advertises its address to clients when binding to `0.0.0.0`. There has also been some work in the python client that adds the ability to specify an address manually: https://github.com/pilosa/python-pilosa/pull/137

Do you think these address the issues you were seeing?

**Comment by WaaX** [comment]
thanks, this look perfect with use_manual_address=True in python. thanks!
