### ISSUE TITLE
Client uses wrong connect_timeout and socket_timeout values during `import_field`

### ISSUE THREAD

**Issue by DjDeepDive** [pilosa/python-pilosa#151]
**Issue:**

**`import_field`** function times out incorrectly when trying to import data.

**Reason:**

The Client class divides incoming `connect_timeout` and `socket_timeout` by 1000.0 before storing those values as a member variables in **`__init__`**

https://github.com/pilosa/python-pilosa/blob/0d75e2337e674c38f4825fedc6d5fa690cb5e6ef/pilosa/client.py#L120-L121

The `import_field` function calls `_import_data`, which instantiates a new `Client` with existing values, which causes the timeouts to be divided by 1000.0 again in the new client, causing unintended timeouts.

https://github.com/pilosa/python-pilosa/blob/0d75e2337e674c38f4825fedc6d5fa690cb5e6ef/pilosa/client.py#L362-L373

Possibly a fix would be to re-multiply the values by 1000 before passing them into the Client, in the for loop starting at line 364:
```
    if k in ["connect_timeout", "socket_timeout"]:
        client_params[k] = 1000.0 * v
```

**Comment by travisturner** [comment]
Thanks @DjDeepDive!
I submitted your suggestion in #152. For some reason there's a test failure in CI, so we're looking into that.

**Comment by DjDeepDive** [comment]
Didn't look like it ever got merged?

**Comment by mkuzdowicz** [comment]
hey i think something simple as that will fix that issue https://github.com/pilosa/python-pilosa/pull/155
