### ISSUE TITLE
hwo to user method "Rows(field)"

### ISSUE THREAD

**Issue by Danny19580907** [pilosa/python-pilosa#158]
like the title,i can't understand the method Rows(field)

i performe this method,but the erros is following:
curl "localhost:10101/index/user/query" -X POST -d 'Rows(age)'
{"error":"parsing: parsing: \nparse error near IDENT (line 1 symbol 6 - line 1 symbol 9):\n\"age\"\n"}
or
curl "localhost:10101/index/user/query" -X POST -d 'Rows(field="age")'
{"error":"executing: map reduce: unknown call: Rows"}

please help me!!!!!!!!!!
hwo to use it

**Comment by jaffee** [comment]
What type of field is "age"? If it's an integer field I don't think that query will work.

What version of Pilosa are you using? I'm not sure when the "Rows" query was added, but possible it's only in a newer version.

**Comment by jaffee** [comment]
I'm also going to close this because it is purely Pilosa related and not python-pilosa
