### ISSUE TITLE
Implement import functionality in client libary

### ISSUE THREAD

**Issue by codysoyland** [pilosa/python-pilosa#18]
Large numbers of SetBits can take awhile to process. Maybe we should expose the import endpoint in the client library in an idiomatic way.

**Comment by jaffee** [comment]
@yuce - can you confirm that this still needs to be done?

**Comment by yuce** [comment]
@jaffee Yes, this is still not implemented for the python client.

**Comment by yuce** [comment]
This feature is implemented: https://github.com/pilosa/python-pilosa/commit/50b9b4ed85d49120fed62abf0230dfdd57466117 . Closing the ticket.
