### ISSUE TITLE
Support TopN with no "n" argument

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/python-pilosa#30]

**Comment by yuce** [comment]
@alanbernstein Can't remember the exact conversation, but I think last time we decided to use `TopN` always with `n` (unless I remember it wrong).

**Comment by alanbernstein** [comment]
I know it's come up before, I also don't remember the details. Actually it appears that n=0 returns the same "full list" result as unspecified n, so it doesn't matter if clients support this.
