### ISSUE TITLE
cilent query function not working properly

### ISSUE THREAD

**Issue by fivejjs** [pilosa/python-pilosa#97]
I am running the samples with aminials index and traits frame
```Python
response = client.query(captivity.gt(100))
print(response.result.bitmap.bits)
```
result is empty list
```Python
[]
```

But I can query with requests:
```Python
import requests
sess = requests.Session()
resp = sess.post('http://localhost:10101/index/animals/query', data="Range(frame='traits', captivity > 100)")

## resp.json()
# {'results': [{'attrs': {}, 'bits': [2, 4, 5, 8, 11, 12]}]}
```

**Comment by yuce** [comment]
Hi @fivejjs . Can you please try `pip install pilosa==0.8.2` when installing the Python client? Version 0.8.3 is only compatible with the master branch of Pilosa server. We hid that version, but I think due to the recent changes on PYPI it is installed when the version is not specified.

**Comment by yuce** [comment]
@fivejjs Did using version 0.8.2 client fix this problem?
